[package]
name = "orbit"
version = "0.1.0"
edition = "2024"

[features]
default = []
portable = ["orbit-core/portable"]

[dependencies]
# 内部依赖
orbit-core = { path = "../orbit-core" }

# 工作区依赖
tokio.workspace = true
clap.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
indicatif.workspace = true
comfy-table.workspace = true
