[package]
name = "orbit-bundle-format"
version = "0.5.1"
edition = "2024"
license = "MIT"

[dependencies]
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
toml.workspace = true
url.workspace = true
zip.workspace = true
